#include <iostream>
#include <vector>
#include <string>
#include <unordered_map>
#include <random>
#include <cmath>
#include <algorithm>
#include <numeric>
#include <sstream>
#include <iterator>
#include <cassert>

// Hyperparameter settings
const int EMBEDDING_SIZE = 128; // Size of Embedding vector
const int HIDDEN_SIZE = 512; // Size of Hidden layer
const int OUTPUT_SIZE = 128; // Size of Final print
const int NUM_HEADS = 8; // Number of MHA
const int CONTEXT_SIZE = 1024; // Size of Context
const double LEARNING_RATE = 0.01; // Learning Rate
const double EPSILON = 1e-10; // Epsilon
const int EPOCH_NUM = 30; // Number of epoch
const double BETA1 = 0.9; // BetaA for Adam
const double BETA2 = 0.999; // BetaB for Adam
const std::string PAD_TOKEN = "<PAD>"; // Pad token

std::vector<std::vector<double>> generateWeightMatrix(int inputSize, int outputSize) {
    std::vector<std::vector<double>> weightMatrix(inputSize, std::vector<double>(outputSize));
    std::random_device rd;
    std::mt19937 gen(rd());
    std::normal_distribution<> dis(0.0, 1.0 / std::sqrt(inputSize));
    for (int i = 0; i < inputSize; ++i) {
        for (int j = 0; j < outputSize; ++j) {
            weightMatrix[i][j] = dis(gen);
        }
    }
    return weightMatrix;
}

std::vector<double> transformEmbedding(const std::vector<double>& inputEmbedding,
    const std::vector<std::vector<double>>& weightMatrix) {
    std::vector<double> transformedEmbedding(weightMatrix[0].size(), 0.0);
    for (size_t j = 0; j < weightMatrix[0].size(); ++j) {
        for (size_t i = 0; i < inputEmbedding.size(); ++i) {
            transformedEmbedding[j] += inputEmbedding[i] * weightMatrix[i][j];
        }
    }
    return transformedEmbedding;
}

std::vector<double> generateRandomEmbedding() {
    std::vector<double> embedding(EMBEDDING_SIZE);
    std::random_device rd;
    std::mt19937 gen(rd());
    std::normal_distribution<> dis(0.0, 1.0);
    for (int i = 0; i < EMBEDDING_SIZE; ++i) {
        embedding[i] = dis(gen);
    }
    return embedding;
}

double cosineSimilarity(const std::vector<double>& vec1, const std::vector<double>& vec2) {
    double dotProduct = 0.0, normA = 0.0, normB = 0.0;
    for (size_t i = 0; i < vec1.size(); ++i) {
        dotProduct += vec1[i] * vec2[i];
        normA += vec1[i] * vec1[i];
        normB += vec2[i] * vec2[i];
    }
    return dotProduct / (std::sqrt(normA + EPSILON) * std::sqrt(normB + EPSILON));
}

std::vector<std::string> tokenize(const std::string& sentence) {
    std::istringstream stream(sentence);
    std::vector<std::string> tokens((std::istream_iterator<std::string>(stream)),
        std::istream_iterator<std::string>());
    return tokens;
}

std::vector<double> aggregateEmbeddings(const std::vector<std::string>& tokens,
    const std::unordered_map<std::string, std::vector<double>>& embeddings) {
    std::vector<double> aggregated(EMBEDDING_SIZE, 0.0);
    for (const auto& token : tokens) {
        auto it = embeddings.find(token);
        if (it != embeddings.end()) {
            for (size_t i = 0; i < EMBEDDING_SIZE; ++i) {
                aggregated[i] += it->second[i];
            }
        }
        else if (embeddings.find(PAD_TOKEN) != embeddings.end()) {
            for (size_t i = 0; i < EMBEDDING_SIZE; ++i) {
                aggregated[i] += embeddings.at(PAD_TOKEN)[i];
            }
        }
    }
    for (auto& value : aggregated) {
        value /= tokens.size();
    }
    return aggregated;
}

std::vector<double> softmax(const std::vector<double>& logits) {
    std::vector<double> exps(logits.size());
    double sum = 0.0;
    for (size_t i = 0; i < logits.size(); ++i) {
        exps[i] = std::exp(logits[i]);
        sum += exps[i];
    }
    for (auto& exp : exps) {
        exp /= sum;
    }
    return exps;
}

double crossEntropyLoss(const std::vector<double>& predicted, const std::vector<double>& target) {
    double loss = 0.0;
    for (size_t i = 0; i < predicted.size(); ++i) {
        loss -= target[i] * std::log(predicted[i] + EPSILON);
    }
    return loss;
}

void normalizeEmbedding(std::vector<double>& embedding) {
    double norm = std::sqrt(std::inner_product(embedding.begin(), embedding.end(), embedding.begin(), 0.0));
    for (auto& value : embedding) {
        value /= (norm + EPSILON);
    }
}

std::vector<double> selfAttention(const std::vector<double>& query, const std::vector<double>& key, const std::vector<double>& value) {
    double score = std::inner_product(query.begin(), query.end(), key.begin(), 0.0);
    score = std::exp(score / std::sqrt(EMBEDDING_SIZE));
    std::vector<double> attentionOutput(EMBEDDING_SIZE);
    for (size_t i = 0; i < EMBEDDING_SIZE; ++i) {
        attentionOutput[i] = score * value[i];
    }
    return attentionOutput;
}

std::vector<double> multiHeadAttention(const std::vector<double>& query,
    const std::vector<std::vector<double>>& keys,
    const std::vector<std::vector<double>>& values) {
    std::vector<double> multiHeadOutput(EMBEDDING_SIZE, 0.0);
    int headSize = EMBEDDING_SIZE / NUM_HEADS;
    for (int h = 0; h < NUM_HEADS; ++h) {
        std::vector<double> headOutput(headSize, 0.0);
        for (size_t i = 0; i < keys.size(); ++i) {
            auto attentionOutput = selfAttention(query, keys[i], values[i]);
            for (int j = 0; j < headSize; ++j) {
                int index = h * headSize + j;
                if (index < attentionOutput.size()) {
                    headOutput[j] += attentionOutput[index];
                }
            }
        }
        for (int j = 0; j < headSize; ++j) {
            multiHeadOutput[h * headSize + j] = headOutput[j];
        }
    }
    return multiHeadOutput;
}

std::string predictNextToken(const std::vector<double>& contextEmbedding,
    const std::unordered_map<std::string, std::vector<double>>& embeddings) {
    double maxSimilarity = -1.0;
    std::string nextToken;
    for (const auto& pair : embeddings) {
        double similarity = cosineSimilarity(contextEmbedding, pair.second);
        if (similarity > maxSimilarity) {
            maxSimilarity = similarity;
            nextToken = pair.first;
        }
    }
    return nextToken;
}

void padAndMask(std::vector<std::string>& tokens, int contextSize) {
    if (tokens.size() < contextSize) {
        tokens.insert(tokens.end(), contextSize - tokens.size(), PAD_TOKEN);
    }
}

void trainModel(std::unordered_map<std::string, std::vector<double>>& embeddings,
    const std::vector<std::string>& trainingData) {
    std::unordered_map<std::string, unsigned int> tokenToIndex;
    for (size_t i = 0; i < trainingData.size(); ++i) {
        tokenToIndex[trainingData[i]] = i;
    }

    auto weightMatrix = generateWeightMatrix(HIDDEN_SIZE, OUTPUT_SIZE);

    std::unordered_map<std::string, std::vector<double>> m, v;
    for (const auto& token : trainingData) {
        m[token] = std::vector<double>(EMBEDDING_SIZE, 0.0);
        v[token] = std::vector<double>(EMBEDDING_SIZE, 0.0);
    }

    for (int epoch = 0; epoch < EPOCH_NUM; ++epoch) {
        double totalLoss = 0.0;
        for (size_t i = 0; i < trainingData.size() - CONTEXT_SIZE; ++i) {
            std::vector<std::string> context(trainingData.begin() + i, trainingData.begin() + i + CONTEXT_SIZE);
            padAndMask(context, CONTEXT_SIZE);

            if (i + CONTEXT_SIZE < trainingData.size()) {
                std::string correctToken = trainingData[i + CONTEXT_SIZE];
                std::vector<double> contextEmbedding = aggregateEmbeddings(context, embeddings);
                std::vector<double> correctEmbedding = embeddings[correctToken];

                auto transformedContextEmbedding = transformEmbedding(contextEmbedding, weightMatrix);
                auto multiHeadOutput = multiHeadAttention(transformedContextEmbedding, { transformedContextEmbedding }, { transformedContextEmbedding });
                normalizeEmbedding(multiHeadOutput);

                auto predictedEmbedding = softmax(multiHeadOutput);

                std::vector<double> correctEmbeddingOneHot(predictedEmbedding.size(), 0.0);
                auto it = tokenToIndex.find(correctToken);
                if (it != tokenToIndex.end() && it->second < correctEmbeddingOneHot.size()) {
                    correctEmbeddingOneHot[it->second] = 1.0;
                }

                double loss = crossEntropyLoss(predictedEmbedding, correctEmbeddingOneHot);
                totalLoss += loss;

                for (size_t j = 0; j < EMBEDDING_SIZE; ++j) {
                    double g = (predictedEmbedding[j] - correctEmbeddingOneHot[j]);
                    m[correctToken][j] = BETA1 * m[correctToken][j] + (1 - BETA1) * g;
                    v[correctToken][j] = BETA2 * v[correctToken][j] + (1 - BETA2) * g * g;

                    double m_hat = m[correctToken][j] / (1 - pow(BETA1, epoch + 1));
                    double v_hat = v[correctToken][j] / (1 - pow(BETA2, epoch + 1));

                    embeddings[correctToken][j] -= LEARNING_RATE * m_hat / (sqrt(v_hat) + EPSILON);
                }

                normalizeEmbedding(embeddings[correctToken]);
            }
        }
        std::cout << "Epoch " << epoch + 1 << " Loss: " << totalLoss / trainingData.size() << "\n    [ ===================== " << epoch+1 << " / " << EPOCH_NUM << " ]" << "\n";
    }
}

void evaluateModel(const std::unordered_map<std::string, std::vector<double>>& embeddings,
    const std::vector<std::string>& testData) {
    int correct = 0;
    for (size_t i = 0; i < testData.size() - CONTEXT_SIZE; ++i) {
        std::vector<std::string> context(testData.begin() + i, testData.begin() + i + CONTEXT_SIZE);
        padAndMask(context, CONTEXT_SIZE);

        if (i + CONTEXT_SIZE < testData.size()) {
            std::string correctToken = testData[i + CONTEXT_SIZE];
            std::vector<double> contextEmbedding = aggregateEmbeddings(context, embeddings);
            std::string predictedToken = predictNextToken(contextEmbedding, embeddings);
            if (predictedToken == correctToken) {
                correct++;
            }
        }
    }

        double accuracy = static_cast<double>(correct) / (testData.size() - CONTEXT_SIZE) * 100;
        std::cout << "Accuracy: " << accuracy << "%\n";
}

int main() {

    std::cout << "# vAI NLP model version 1.0.3\n\nTraining [ in progress ]\n * This task may take up to 20 minutes\n";

    std::vector<std::string> trainingData = {
        "I", "went", "to", "the", "store", "to", "buy", "some", "groceries", "The", "weather", "is", "nice", "today", "Let's", "go", "for", "a", "walk",
        "I", "love", "spending", "time", "with", "my", "family", "She", "is", "reading", "a", "book", "He", "is", "playing", "the", "guitar",
        "They", "are", "watching", "a", "movie", "We", "are", "having", "dinner", "together", "I", "have", "a", "meeting", "at", "work", "tomorrow",
        "Can", "you", "pass", "me", "the", "salt", "What", "did", "you", "do", "yesterday", "I", "went", "for", "a", "run", "in", "the", "morning",
        "He", "is", "working", "on", "a", "new", "project", "She", "is", "taking", "a", "nap", "The", "kids", "are", "playing", "in", "the", "park",
        "I", "need", "to", "go", "to", "the", "bank", "today", "Do", "you", "want", "to", "come", "with", "me", "We", "are", "planning", "a", "trip",
        "next", "month", "She", "is", "baking", "cookies", "right", "now", "He", "is", "fixing", "his", "car", "I", "am", "learning", "to", "play",
        "the", "piano", "They", "are", "building", "a", "new", "house", "We", "are", "going", "to", "the", "beach", "this", "weekend", "She", "is",
        "studying", "for", "her", "exams", "He", "is", "writing", "a", "letter", "to", "his", "friend", "I", "am", "looking", "for", "a", "new",
        "job", "They", "are", "cleaning", "the", "house", "We", "are", "decorating", "the", "Christmas", "tree", "She", "is", "knitting", "a",
        "scarf", "He", "is", "drawing", "a", "picture", "I", "am", "reading", "the", "news", "They", "are", "discussing", "a", "new", "idea",
        "We", "are", "celebrating", "our", "anniversary", "She", "is", "watching", "her", "favorite", "show", "He", "is", "repairing", "the",
        "fence", "I", "am", "writing", "a", "report", "for", "work", "They", "are", "playing", "a", "board", "game", "We", "are", "hosting",
        "a", "dinner", "party", "She", "is", "planting", "flowers", "in", "the", "garden", "He", "is", "painting", "the", "walls", "I", "am",
        "making", "a", "birthday", "cake", "They", "are", "shopping", "for", "new", "clothes", "We", "are", "going", "to", "a", "concert",
        "She", "is", "organizing", "her", "closet", "He", "is", "taking", "out", "the", "trash", "I", "am", "checking", "my", "email",
        "We", "are", "visiting", "our", "grandparents", "this", "weekend", "She", "is", "making", "a", "scrapbook", "He", "is", "washing", "the", "dishes",
        "I", "am", "learning", "to", "speak", "Spanish", "They", "are", "attending", "a", "wedding", "We", "are", "going", "to", "the", "zoo",
        "She", "is", "playing", "tennis", "He", "is", "building", "a", "model", "airplane", "I", "am", "volunteering", "at", "the", "animal", "shelter",
        "They", "are", "going", "on", "a", "road", "trip", "We", "are", "having", "a", "barbecue", "She", "is", "taking", "a", "photography", "class",
        "He", "is", "learning", "to", "cook", "I", "am", "going", "to", "the", "gym", "They", "are", "watching", "the", "sunset", "We", "are", "making",
        "a", "time", "capsule", "She", "is", "writing", "a", "poem", "He", "is", "fixing", "the", "leaky", "faucet", "I", "am", "gardening", "They", "are",
        "playing", "video", "games", "We", "are", "going", "to", "a", "picnic", "She", "is", "learning", "to", "sew", "He", "is", "painting", "a", "mural",
        "I", "am", "writing", "a", "novel", "They", "are", "going", "camping", "We", "are", "flying", "kites", "She", "is", "taking", "a", "dance", "class",
        "He", "is", "building", "a", "treehouse", "I", "am", "going", "to", "the", "library", "They", "are", "watching", "a", "play", "We", "are", "having",
        "a", "game", "night", "She", "is", "learning", "to", "play", "the", "violin", "He", "is", "fixing", "the", "bike", "I", "am", "baking", "bread",
        "They", "are", "watching", "the", "stars", "We", "are", "making", "a", "video", "She", "is", "drawing", "a", "portrait", "He", "is", "repairing",
        "the", "roof", "I", "am", "writing", "a", "song", "They", "are", "going", "hiking", "We", "are", "having", "a", "movie", "marathon", "She", "is",
        "learning", "to", "knit", "He", "is", "painting", "the", "garage", "I", "am", "going", "for", "a", "swim", "They", "are", "playing", "chess",
        "We", "are", "making", "a", "puzzle", "She", "is", "writing", "a", "letter", "He", "is", "fixing", "the", "car", "I", "am", "learning", "to",
        "play", "the", "guitar", "They", "are", "watching", "a", "documentary", "We", "are", "having", "a", "potluck", "She", "is", "taking", "a",
        "singing", "class", "He", "is", "building", "a", "shed", "I", "am", "going", "to", "the", "spa", "They", "are", "watching", "the", "birds",
        "We", "are", "making", "a", "sandcastle", "She", "is", "writing", "a", "diary", "He", "is", "fixing", "the", "computer", "I", "am", "learning",
        "to", "code", "They", "are", "going", "fishing", "We", "are", "having", "a", "cookout", "She", "is", "drawing", "a", "landscape", "He", "is",
        "painting", "the", "fence", "I", "am", "going", "to", "the", "museum", "They", "are", "playing", "soccer", "We", "are", "making", "a", "scrapbook",
        "She", "is", "writing", "a", "journal", "He", "is", "fixing", "the", "lawnmower", "I", "am", "learning", "to", "skate", "They", "are", "watching",
        "a", "football", "game", "We", "are", "having", "a", "birthday", "party", "She", "is", "taking", "a", "photography", "class", "He", "is", "building",
        "a", "birdhouse", "I", "am", "going", "to", "the", "mall", "They", "are", "watching", "the", "fireworks", "We", "are", "making", "a", "snowman",
        "She", "is", "writing", "a", "blog", "He", "is", "fixing", "the", "shower", "I", "am", "learning", "to", "drive", "They", "are", "going", "to",
        "the", "park", "We", "are", "having", "a", "garage", "sale", "She", "is", "drawing", "a", "comic", "He", "is", "painting", "the", "deck",
        "I", "am", "going", "for", "a", "bike", "ride", "They", "are", "playing", "basketball", "We", "are", "making", "a", "scrapbook",
        "She", "is", "writing", "a", "book", "He", "is", "fixing", "the", "TV", "I", "am", "learning", "to", "play", "the", "drums",
        "They", "are", "watching", "a", "baseball", "game", "We", "are", "having", "a", "potluck", "She", "is", "taking", "a", "cooking",
        "class", "He", "is", "building", "a", "robot", "I", "am", "going", "to", "the", "theater", "They", "are", "watching", "the",
        "parade", "We", "are", "making", "a", "scrapbook", "She", "is", "writing", "a", "song", "He", "is", "fixing", "the", "sink",
        "I", "am", "learning", "to", "dance", "They", "are", "going", "to", "the", "beach", "We", "are", "having", "a", "picnic",
        "She", "is", "drawing", "a", "self-portrait", "He", "is", "painting", "the", "house", "I", "am", "going", "for", "a", "run",
        "They", "are", "playing", "volleyball", "We", "are", "making", "a", "scrapbook", "She", "is", "writing", "a", "play", "He",
        "is", "fixing", "the", "stove", "I", "am", "learning", "to", "play", "the", "violin", "They", "are", "watching", "a",
        "basketball", "game", "We", "are", "having", "a", "family", "reunion", "She", "is", "taking", "a", "gardening", "class",
        "He", "is", "building", "a", "treehouse", "I", "am", "going", "to", "the", "gym", "They", "are", "watching", "the",
        "sunrise", "We", "are", "making", "a", "video", "She", "is", "writing", "a", "letter", "He", "is", "fixing", "the",
        "microwave", "I", "am", "learning", "to", "play", "the", "saxophone", "They", "are", "going", "to", "the", "circus",
        "We", "are", "having", "a", "party", "She", "is", "drawing", "a", "landscape", "He", "is", "painting", "the", "shed",
        "I", "am", "going", "for", "a", "hike", "They", "are", "playing", "baseball", "We", "are", "making", "a", "scrapbook",
        "She", "is", "writing", "a", "novel", "He", "is", "fixing", "the", "air", "conditioner", "I", "am", "learning", "to",
        "play", "the", "flute", "They", "are", "watching", "a", "hockey", "game", "We", "are", "having", "a", "block", "party",
        "She", "is", "taking", "a", "knitting", "class", "He", "is", "building", "a", "model", "train", "I", "am", "going", "to",
        "the", "park", "They", "are", "watching", "the", "balloons", "We", "are", "making", "a", "scrapbook", "She", "is", "writing",
        "a", "poem", "He", "is", "fixing", "the", "dishwasher", "I", "am", "learning", "to", "play", "the", "trumpet", "They", "are",
        "going", "to", "the", "lake", "We", "are", "having", "a", "beach", "party", "She", "is", "drawing", "a", "still", "life",
        "He", "is", "painting", "the", "ceiling", "I", "am", "going", "for", "a", "drive", "They", "are", "playing", "tennis",
        "We", "are", "making", "a", "scrapbook", "She", "is", "writing", "a", "diary", "He", "is", "fixing", "the", "windows",
        "I", "am", "learning", "to", "play", "the", "clarinet", "They", "are", "watching", "a", "soccer", "game", "We", "are",
        "having", "a", "pool", "party", "She", "is", "taking", "a", "pottery", "class", "He", "is", "building", "a", "wooden",
        "boat", "I", "am", "going", "to", "the", "bakery", "They", "are", "watching", "the", "birds", "We", "are", "making",
        "a", "scrapbook", "She", "is", "writing", "a", "short", "story", "He", "is", "fixing", "the", "garage", "I", "am",
        "learning", "to", "play", "the", "harp", "They", "are", "going", "to", "the", "mountains", "We", "are", "having",
        "a", "potluck", "She", "is", "drawing", "a", "manga", "He", "is", "painting", "the", "door", "I", "am", "going",
        "for", "a", "stroll", "They", "are", "playing", "golf", "We", "are", "making", "a", "scrapbook", "She", "is",
        "writing", "a", "screenplay", "He", "is", "fixing", "the", "roof", "I", "am", "learning", "to", "play", "the",
        "accordion", "They", "are", "watching", "a", "cricket", "match", "We", "are", "having", "a", "gathering",
        "She", "is", "taking", "a", "drama", "class", "He", "is", "building", "a", "bridge", "I", "am", "going",
        "to", "the", "cafeteria", "They", "are", "watching", "the", "sunset", "We", "are", "making", "a",
        "scrapbook", "She", "is", "writing", "a", "letter", "He", "is", "fixing", "the", "radiator", "I",
        "am", "learning", "to", "play", "the", "cello", "They", "are", "going", "to", "the", "forest",
        "We", "are", "having", "a", "retreat", "She", "is", "drawing", "a", "cityscape", "He", "is",
        "painting", "the", "furniture", "I", "am", "going", "for", "a", "run", "They", "are", "playing",
        "ping-pong", "We", "are", "making", "a", "scrapbook", "She", "is", "writing", "a", "storybook",
        "He", "is", "fixing", "the", "heater", "I", "am", "learning", "to", "play", "the", "oboe",
        "They", "are", "watching", "a", "rugby", "match", "We", "are", "having", "a", "get-together",
        "She", "is", "taking", "a", "photography", "course", "He", "is", "building", "a", "model",
        "rocket", "I", "am", "going", "to", "the", "gym", "They", "are", "watching", "the",
        "fishing", "boats", "We", "are", "making", "a", "scrapbook", "She", "is", "writing",
        "a", "biography", "He", "is", "fixing", "the", "chimney", "I", "am", "learning",
        "to", "play", "the", "bassoon", "They", "are", "going", "to", "the", "theater",
        "We", "are", "having", "a", "gala", "She", "is", "drawing", "a", "blueprint",
        "He", "is", "painting", "the", "windowsill", "I", "am", "going", "for", "a",
        "sprint", "They", "are", "playing", "cricket", "We", "are", "making", "a",
        "scrapbook", "She", "is", "writing", "a", "letter", "He", "is", "fixing",
        "the", "pipe", "I", "am", "learning", "to", "play", "the", "tambourine",
        "They", "are", "watching", "a", "track", "meet", "We", "are", "having",
        "a", "celebration", "She", "is", "taking", "a", "sculpting", "class",
        "He", "is", "building", "a", "doghouse", "I", "am", "going", "to",
        "the", "fair", "They", "are", "watching", "the", "planes", "We",
        "are", "making", "a", "scrapbook", "She", "is", "writing", "a",
        "letter", "He", "is", "fixing", "the", "ceiling", "I", "am",
        "learning", "to", "play", "the", "fiddle", "They", "are",
        "going", "to", "the", "concert", "We", "are", "having",
        "a", "festival", "She", "is", "drawing", "a", "building",
        "He", "is", "painting", "the", "sidewalk", "I", "am",
        "going", "for", "a", "run", "They", "are", "playing",
        "badminton", "We", "are", "making", "a", "scrapbook",
        "She", "is", "writing", "a", "play", "He", "is",
        "fixing", "the", "light", "I", "am", "learning",
        "to", "play", "the", "tuba", "They", "are",
        "watching", "a", "swimming", "competition",
        "We", "are", "having", "a", "reunion",
        "She", "is", "taking", "a", "writing",
        "class", "He", "is", "building",
        "a", "sandbox", "I", "am",
        "going", "to", "the",
        "spa", "They",
        "are", "watching",
        "the", "boats",
        "We", "are",
        "making", "a",
        "scrapbook",
        "She", "is",
        "writing",
        "a", "letter",
        "He", "is",
        "fixing", "the",
        "fan", "I",
        "am", "learning",
        "to", "play", "the",
        "viola", "They",
        "are", "going",
        "to", "the",
        "circus", "We",
        "are", "having",
        "a", "celebration",
        "She", "is",
        "drawing", "a",
        "still", "life",
        "He", "is",
        "painting",
        "the", "bench",
        "I", "am",
        "going", "for",
        "a", "run", "They",
        "are", "playing",
        "football", "We",
        "are", "making",
        "a", "scrapbook",
        "She", "is",
        "writing", "a",
        "novel", "He",
        "is", "fixing",
        "the", "furnace",
        "I", "am", "learning",
        "to", "play", "the",
        "harp", "They",
        "are", "watching",
        "a", "wrestling",
        "match", "We",
        "are", "having",
        "a", "banquet",
        "She", "is",
        "taking", "a",
        "dance", "class",
        "He", "is",
        "building", "a",
        "fort", "I",
        "am", "going",
        "to", "the",
        "park", "They",
        "are", "watching",
        "the", "clouds",
        "We", "are",
        "making", "a",
        "scrapbook", "She",
        "is", "writing",
        "a", "memoir",
        "He", "is",
        "fixing", "the",
        "chimney", "I",
        "am", "learning",
        "to", "play", "the",
        "accordion", "They",
        "are", "going", "to",
        "the", "circus", "We",
        "are", "having", "a",
        "party", "She",
        "is", "drawing", "a",
        "picture", "He",
        "is", "painting",
        "the", "fence",
        "I", "am", "going",
        "for", "a", "walk",
        "They", "are",
        "playing", "soccer",
        "We", "are",
        "making", "a",
        "scrapbook", "She",
        "is", "writing",
        "a", "letter",
        "He", "is",
        "fixing", "the",
        "roof", "I",
        "am", "learning",
        "to", "play", "the",
        "guitar", "They",
        "are", "watching",
        "a", "tennis",
        "match", "We",
        "are", "having",
        "a", "gathering",
        "She", "is",
        "taking", "a",
        "cooking", "class",
        "He", "is",
        "building", "a",
        "boat", "I",
        "am", "going",
        "to", "the", "gym",
        "They", "are",
        "watching", "the",
        "stars", "We",
        "are", "making",
        "a", "scrapbook",
        "She", "is",
        "writing", "a",
        "letter", "He",
        "is", "fixing",
        "the", "car", "I",
        "am", "learning",
        "to", "play", "the",
        "piano", "They",
        "are", "watching",
        "a", "movie", "We",
        "are", "having",
        "a", "barbecue",
        "She", "is",
        "drawing", "a",
        "cartoon", "He",
        "is", "painting",
        "the", "garage",
        "I", "am", "going",
        "for", "a", "swim",
        "They", "are",
        "playing", "golf",
        "We", "are",
        "making", "a",
        "scrapbook", "She",
        "is", "writing",
        "a", "letter",
        "He", "is",
        "fixing", "the",
        "stove", "I",
        "am", "learning",
        "to", "play", "the",
        "violin", "They",
        "are", "watching",
        "a", "basketball",
        "game", "We",
        "are", "having",
        "a", "reunion",
        "She", "is",
        "taking", "a",
        "photography", "class",
        "He", "is", "building",
        "a", "treehouse", "I",
        "am", "going", "to",
        "the", "store", "They",
        "are", "watching", "the",
        "sunset", "We",
        "are", "making", "a",
        "scrapbook", "She",
        "is", "writing", "a",
        "poem", "He",
        "is", "fixing",
        "the", "leaky", "faucet",
        "I", "am", "learning",
        "to", "play", "the",
        "guitar", "They",
        "are", "going", "on",
        "a", "road", "trip",
        "We", "are", "having",
        "a", "game", "night",
        "She", "is", "drawing",
        "a", "portrait", "He",
        "is", "painting",
        "the", "garage",
        "I", "am", "going",
        "for", "a", "swim",
        "They", "are", "playing",
        "basketball", "We",
        "are", "making", "a",
        "scrapbook", "She",
        "is", "writing",
        "a", "letter", "He",
        "is", "fixing",
        "the", "TV", "I",
        "am", "learning",
        "to", "play", "the",
        "drums", "They",
        "are", "watching",
        "a", "baseball",
        "game", "We",
        "are", "having",
        "a", "potluck", "She",
        "is", "taking", "a",
        "singing", "class",
        "He", "is", "building",
        "a", "shed", "I",
        "am", "going", "to",
        "the", "spa", "They",
        "are", "watching", "the",
        "birds", "We",
        "are", "making", "a",
        "scrapbook", "She",
        "is", "writing", "a",
        "diary", "He",
        "is", "fixing",
        "the", "computer", "I",
        "am", "learning",
        "to", "code", "They",
        "are", "going", "fishing",
        "We", "are", "having",
        "a", "cookout", "She",
        "is", "drawing", "a",
        "landscape", "He",
        "is", "painting",
        "the", "fence", "I",
        "am", "going", "to",
        "the", "museum", "They",
        "are", "playing", "soccer",
        "We", "are", "making",
        "a", "scrapbook", "She",
        "is", "writing", "a",
        "journal", "He",
        "is", "fixing",
        "the", "lawnmower", "I",
        "am", "learning",
        "to", "skate", "They",
        "are", "watching", "a",
        "football", "game", "We",
        "are", "having", "a",
        "birthday", "party", "She",
        "is", "taking", "a",
        "photography", "class", "He",
        "is", "building", "a",
        "birdhouse", "I",
        "am", "going", "to",
        "the", "mall", "They",
        "are", "watching", "the",
        "fireworks", "We",
        "are", "making", "a",
        "snowman", "She",
        "is", "writing", "a",
        "blog", "He",
        "is", "fixing",
        "the", "shower", "I",
        "am", "learning",
        "to", "drive", "They",
        "are", "going", "to",
        "the", "park", "We",
        "are", "having",
        "a", "garage", "sale",
        "She", "is", "drawing",
        "a", "comic", "He",
        "is", "painting",
        "the", "deck", "I",
        "am", "going", "for",
        "a", "bike", "ride",
        "They", "are", "playing",
        "basketball", "We",
        "are", "making",
        "a", "scrapbook", "She",
        "is", "writing", "a",
        "book", "He",
        "is", "fixing",
        "the", "TV", "I",
        "am", "learning",
        "to", "play", "the",
        "drums", "They",
        "are", "watching", "a",
        "baseball", "game", "We",
        "are", "having",
        "a", "potluck", "She",
        "is", "taking", "a",
        "singing", "class",
        "He", "is", "building",
        "a", "shed", "I",
        "am", "going", "to",
        "the", "spa", "They",
        "are", "watching", "the",
        "birds", "We",
        "are", "making", "a",
        "scrapbook", "She",
        "is", "writing", "a",
        "diary", "He",
        "is", "fixing",
        "the", "computer", "I",
        "am", "learning",
        "to", "code", "They",
        "are", "going", "fishing",
        "We", "are", "having",
        "a", "cookout", "She",
        "is", "drawing", "a",
        "landscape", "He",
        "is", "painting",
        "the", "fence", "I",
        "am", "going", "to",
        "the", "museum", "They",
        "are", "playing", "soccer",
        "We", "are", "making",
        "a", "scrapbook", "She",
        "is", "writing", "a",
        "journal", "He",
        "is", "fixing",
        "the", "lawnmower", "I",
        "am", "learning",
        "to", "skate", "They",
        "are", "watching", "a",
        "football", "game", "We",
        "are", "having", "a",
        "birthday", "party", "She",
        "is", "taking", "a",
        "photography", "class", "He",
        "is", "building", "a",
        "birdhouse", "I",
        "am", "going", "to",
        "the", "mall", "They",
        "are", "watching", "the",
        "fireworks", "We",
        "are", "making", "a",
        "snowman", "She",
        "is", "writing", "a",
        "blog", "He",
        "is", "fixing",
        "the", "shower", "I",
        "am", "learning",
        "to", "drive", "They",
        "are", "going", "to",
        "the", "park", "We",
        "are", "having",
        "a", "garage", "sale",
        "She", "is", "drawing",
        "a", "comic", "He",
        "is", "painting",
        "the", "deck", "I",
        "am", "going", "for",
        "a", "bike", "ride",
        "They", "are", "playing",
        "basketball", "We",
        "are", "making",
        "a", "scrapbook", "She",
        "is", "writing", "a",
        "book", "He",
        "is", "fixing",
        "the", "TV", "I",
        "am", "learning",
        "to", "play", "the",
        "drums", "They",
        "are", "watching", "a",
        "baseball", "game", "We",
        "are", "having",
        "a", "potluck", "She",
        "is", "taking", "a",
        "singing", "class",
        "He", "is", "building",
        "a", "shed", "I",
        "am", "going", "to",
        "the", "spa", "They",
        "are", "watching", "the",
        "birds", "We",
        "are", "making", "a",
        "scrapbook", "She",
        "is", "writing", "a",
        "diary", "He",
        "is", "fixing",
        "the", "computer", "I",
        "am", "learning",
        "to", "code", "They",
        "are", "going", "fishing",
        "We", "are", "having",
        "a", "cookout", "She",
        "is", "drawing", "a",
        "landscape", "He",
        "is", "painting",
        "the", "fence", "I",
        "am", "going", "to",
        "the", "museum", "They",
        "are", "playing", "soccer",
        "We", "are", "making",
        "a", "scrapbook", "She",
        "is", "writing", "a",
        "journal", "He",
        "is", "fixing",
        "the", "lawnmower", "I",
        "am", "learning",
        "to", "skate", "They",
        "are", "watching", "a",
        "football", "game", "We",
        "are", "having", "a",
        "birthday", "party", "She",
        "is", "taking", "a",
        "photography", "class", "He",
        "is", "building", "a",
        "birdhouse", "I",
        "am", "going", "to",
        "the", "mall", "They",
        "are", "watching", "the",
        "fireworks", "We",
        "are", "making", "a",
        "snowman", "She",
        "is", "writing", "a",
        "blog", "He",
        "is", "fixing",
        "the", "shower", "I",
        "am", "learning",
        "to", "drive", "They",
        "are", "going", "to",
        "the", "park", "We",
        "are", "having",
        "a", "garage", "sale",
        "She", "is", "drawing",
        "a", "comic", "He",
        "is", "painting",
        "the", "deck", "I",
        "am", "going", "for",
        "a", "bike", "ride",
        "They", "are", "playing",
        "basketball", "We",
        "are", "making", "a",
        "scrapbook", "She",
        "is", "writing", "a",
        "book", "He",
        "is", "fixing",
        "the", "TV", "I",
        "am", "learning",
        "to", "play", "the",
        "drums", "They",
        "are", "watching", "a",
        "baseball", "game", "We",
        "are", "having",
        "a", "potluck", "She",
        "is", "taking", "a",
        "singing", "class",
        "He", "is", "building",
        "a", "shed", "I",
        "am", "going", "to",
        "the", "spa", "They",
        "are", "watching", "the",
        "birds", "We",
        "are", "making", "a",
        "scrapbook", "She",
        "is", "writing", "a",
        "diary", "He",
        "is", "fixing",
        "the", "computer", "I",
        "am", "learning",
        "to", "code", "They",
        "are", "going", "fishing",
        "We", "are", "having",
        "a", "cookout", "She",
        "is", "drawing", "a",
        "landscape", "He",
        "is", "painting",
        "the", "fence", "I",
        "am", "going", "to",
        "the", "museum", "They",
        "are", "playing", "soccer",
        "We", "are", "making",
        "a", "scrapbook", "She",
        "is", "writing", "a",
        "journal", "He",
        "is", "fixing",
        "the", "lawnmower", "I",
        "am", "learning",
        "to", "skate", "They",
        "are", "watching", "a",
        "football", "game"
    }; // Training data example

    std::vector<std::string> testData = {
        "What", "time", "is", "it", "now", "Where", "is", "the", "nearest", "restaurant", "How", "do", "I", "get", "to", "the", "train", "station",
        "Can", "you", "help", "me", "with", "this", "How", "much", "does", "this", "cost", "What", "is", "your", "name", "Where", "are", "you", "from",
        "Do", "you", "speak", "English", "How", "old", "are", "you", "What", "is", "your", "favorite", "color", "Where", "do", "you", "live",
        "Can", "you", "show", "me", "the", "way", "to", "the", "hotel", "Do", "you", "know", "where", "the", "library", "is", "What", "is", "the",
        "weather", "like", "today", "Can", "you", "recommend", "a", "good", "place", "to", "eat", "How", "far", "is", "it", "to", "the", "airport",
        "What", "is", "the", "best", "way", "to", "get", "downtown", "Do", "you", "have", "a", "map", "Can", "you", "tell", "me", "the", "time",
        "Where", "is", "the", "bathroom", "How", "do", "I", "use", "the", "subway", "Do", "you", "know", "a", "good", "coffee", "shop", "around",
        "here", "What", "is", "the", "meaning", "of", "this", "word", "How", "do", "you", "say", "hello", "in", "Spanish", "Can", "you", "help",
        "me", "find", "a", "taxi", "Where", "can", "I", "buy", "a", "ticket", "for", "the", "bus", "What", "time", "does", "the", "museum", "open",
        "Is", "there", "a", "pharmacy", "nearby", "How", "much", "is", "a", "ticket", "to", "the", "theater", "What", "is", "the", "best", "restaurant",
        "in", "this", "area", "Can", "you", "tell", "me", "how", "to", "get", "to", "the", "beach", "Do", "you", "have", "any", "suggestions", "for",
        "things", "to", "do", "around", "here", "Where", "is", "the", "nearest", "bank", "Can", "you", "help", "me", "find", "a", "good", "hotel",
        "What", "is", "the", "exchange", "rate", "for", "dollars", "to", "euros", "Do", "you", "know", "where", "I", "can", "buy", "a", "sim", "card",
        "for", "my", "phone", "How", "do", "I", "connect", "to", "the", "wifi", "here", "What", "is", "the", "password", "for", "the", "wifi",
        "Where", "can", "I", "rent", "a", "car", "Is", "there", "a", "place", "to", "store", "luggage", "nearby", "How", "much", "does", "it",
        "cost", "to", "take", "a", "taxi", "to", "the", "airport", "Can", "you", "show", "me", "on", "the", "map", "Where", "can", "I", "find",
        "a", "good", "bookstore", "What", "time", "does", "the", "next", "train", "leave", "Can", "you", "recommend", "a", "good", "local", "dish",
        "How", "do", "I", "get", "to", "the", "city", "center", "What", "is", "the", "best", "way", "to", "travel", "around", "the", "city",
        "Do", "you", "have", "a", "tourist", "information", "center", "here", "What", "is", "the", "most", "popular", "tourist", "attraction",
        "around", "here", "Can", "you", "help", "me", "find", "a", "good", "restaurant", "How", "do", "I", "get", "to", "the", "nearest", "hospital",
        "Do", "you", "have", "a", "business", "card", "Can", "you", "tell", "me", "where", "I", "can", "get", "some", "cash", "Is", "there", "a",
        "cash", "machine", "nearby", "What", "time", "does", "the", "supermarket", "close", "Can", "you", "help", "me", "find", "a", "taxi",
        "Do", "you", "know", "any", "good", "places", "to", "visit", "What", "is", "the", "best", "way", "to", "see", "the", "city", "Can",
        "you", "recommend", "a", "good", "place", "to", "stay", "Where", "can", "I", "buy", "tickets", "for", "the", "train", "Is", "there",
        "a", "good", "place", "to", "eat", "around", "here", "How", "do", "I", "get", "to", "the", "airport", "Can", "you", "show", "me",
        "how", "to", "use", "the", "metro", "What", "is", "the", "quickest", "way", "to", "get", "to", "the", "downtown", "area", "Do",
        "you", "have", "a", "local", "map", "Can", "you", "tell", "me", "what", "time", "it", "is", "How", "do", "I", "get", "to",
        "the", "shopping", "mall", "What", "is", "the", "best", "way", "to", "experience", "the", "local", "culture", "Can", "you",
        "recommend", "a", "nice", "cafe", "nearby", "Where", "is", "the", "nearest", "bus", "stop", "How", "much", "is", "the",
        "fare", "for", "the", "bus", "Do", "you", "know", "if", "there", "is", "a", "bike", "rental", "service", "around", "here",
        "Can", "you", "tell", "me", "where", "the", "nearest", "ATM", "is", "How", "do", "I", "get", "to", "the", "museum", "from",
        "here", "What", "is", "the", "best", "way", "to", "spend", "an", "afternoon", "in", "this", "city", "Can", "you", "recommend",
        "a", "good", "park", "to", "visit", "Where", "can", "I", "find", "a", "pharmacy", "near", "here", "How", "much", "is", "a",
        "ticket", "to", "the", "concert", "Do", "you", "know", "if", "there", "are", "any", "guided", "tours", "available", "Can",
        "you", "show", "me", "how", "to", "get", "to", "the", "nearest", "subway", "station", "What", "time", "does", "the", "last",
        "bus", "leave", "How", "do", "I", "get", "to", "the", "museum", "What", "are", "the", "top", "tourist", "attractions",
        "here", "Can", "you", "help", "me", "find", "a", "good", "place", "to", "eat", "How", "much", "does", "it", "cost", "to",
        "rent", "a", "car", "What", "is", "the", "quickest", "way", "to", "get", "to", "the", "train", "station", "Do", "you",
        "know", "any", "good", "places", "to", "shop", "What", "time", "does", "the", "market", "open", "Can", "you", "show", "me",
        "on", "the", "map", "how", "to", "get", "to", "the", "nearest", "beach", "How", "do", "I", "get", "a", "bus", "pass", "What",
        "is", "the", "best", "way", "to", "see", "the", "sights", "around", "here", "Do", "you", "have", "a", "tourist", "guide",
        "Can", "you", "recommend", "a", "good", "place", "to", "stay", "How", "do", "I", "use", "the", "local", "transportation",
        "system", "What", "time", "does", "the", "museum", "close", "Is", "there", "a", "place", "to", "get", "breakfast", "nearby",
        "Can", "you", "help", "me", "find", "a", "doctor", "How", "much", "is", "a", "ticket", "to", "the", "theater", "What", "is",
        "the", "best", "way", "to", "get", "to", "the", "airport", "Do", "you", "know", "a", "good", "place", "to", "have", "lunch",
        "Where", "can", "I", "buy", "tickets", "for", "the", "train", "What", "time", "does", "the", "next", "bus", "arrive", "Can",
        "you", "recommend", "a", "good", "coffee", "shop", "around", "here", "How", "do", "I", "get", "to", "the", "local", "market",
        "What", "is", "the", "best", "way", "to", "explore", "the", "city", "Do", "you", "have", "any", "maps", "available", "Can",
        "you", "tell", "me", "the", "best", "place", "to", "visit", "around", "here", "How", "much", "does", "it", "cost", "to",
        "take", "a", "taxi", "to", "the", "downtown", "area", "What", "is", "the", "quickest", "way", "to", "get", "to", "the",
        "train", "station", "Do", "you", "know", "any", "good", "places", "to", "have", "dinner", "What", "time", "does", "the",
        "supermarket", "open", "Can", "you", "show", "me", "how", "to", "get", "to", "the", "nearest", "park", "How", "do", "I",
        "get", "a", "taxi", "What", "is", "the", "best", "way", "to", "experience", "the", "local", "culture", "Do", "you", "have",
        "any", "suggestions", "for", "places", "to", "visit", "around", "here", "Can", "you", "recommend", "a", "good", "restaurant",
        "in", "this", "area", "What", "time", "does", "the", "bus", "station", "close", "How", "do", "I", "get", "to", "the", "city",
        "center", "What", "is", "the", "quickest", "way", "to", "get", "to", "the", "airport", "Can", "you", "show", "me", "how",
        "to", "use", "the", "metro", "What", "is", "the", "best", "way", "to", "get", "to", "the", "downtown", "area", "Do", "you",
        "have", "a", "local", "map", "Can", "you", "tell", "me", "how", "to", "get", "to", "the", "nearest", "beach", "How", "do",
        "I", "get", "a", "bus", "pass", "What", "is", "the", "best", "way", "to", "see", "the", "sights", "around", "here", "Do",
        "you", "have", "a", "tourist", "guide", "Can", "you", "recommend", "a", "good", "place", "to", "stay", "How", "do", "I",
        "use", "the", "local", "transportation", "system", "What", "time", "does", "the", "museum", "close", "Is", "there", "a",
        "place", "to", "get", "breakfast", "nearby", "Can", "you", "help", "me", "find", "a", "doctor", "How", "much", "is", "a",
        "ticket", "to", "the", "theater", "What", "is", "the", "best", "way", "to", "get", "to", "the", "airport", "Do", "you",
        "know", "a", "good", "place", "to", "have", "lunch", "Where", "can", "I", "buy", "tickets", "for", "the", "train", "What",
        "time", "does", "the", "next", "bus", "arrive", "Can", "you", "recommend", "a", "good", "coffee", "shop", "around", "here",
        "How", "do", "I", "get", "to", "the", "local", "market", "What", "is", "the", "best", "way", "to", "explore", "the", "city",
        "Do", "you", "have", "any", "maps", "available", "Can", "you", "tell", "me", "the", "best", "place", "to", "visit", "around",
        "here", "How", "much", "does", "it", "cost", "to", "take", "a", "taxi", "to", "the", "downtown", "area", "What", "is", "the",
        "quickest", "way", "to", "get", "to", "the", "train", "station", "Do", "you", "know", "any", "good", "places", "to", "have",
        "dinner", "What", "time", "does", "the", "supermarket", "open", "Can", "you", "show", "me", "how", "to", "get", "to", "the",
        "nearest", "park", "How", "do", "I", "get", "a", "taxi", "What", "is", "the", "best", "way", "to", "experience", "the", "local",
        "culture", "Do", "you", "have", "any", "suggestions", "for", "places", "to", "visit", "around", "here", "Can", "you", "recommend",
        "a", "good", "restaurant", "in", "this", "area", "What", "time", "does", "the", "bus", "station", "close", "How", "do", "I",
        "get", "to", "the", "city", "center", "What", "is", "the", "quickest", "way", "to", "get", "to", "the", "airport", "Can", "you",
        "show", "me", "how", "to", "use", "the", "metro", "What", "is", "the", "best", "way", "to", "get", "to", "the", "downtown", "area",
        "Do", "you", "have", "a", "local", "map", "Can", "you", "tell", "me", "how", "to", "get", "to", "the", "nearest", "beach", "How",
        "do", "I", "get", "a", "bus", "pass", "What", "is", "the", "best", "way", "to", "see", "the", "sights", "around", "here", "Do",
        "you", "have", "a", "tourist", "guide", "Can", "you", "recommend", "a", "good", "place", "to", "stay", "How", "do", "I", "use",
        "the", "local", "transportation", "system", "What", "time", "does", "the", "museum", "close", "Is", "there", "a", "place", "to",
        "get", "breakfast", "nearby", "Can", "you", "help", "me", "find", "a", "doctor", "How", "much", "is", "a", "ticket", "to", "the",
        "theater", "What", "is", "the", "best", "way", "to", "get", "to", "the", "airport", "Do", "you", "know", "a", "good", "place", "to",
        "have", "lunch", "Where", "can", "I", "buy", "tickets", "for", "the", "train", "What", "time", "does", "the", "next", "bus", "arrive",
        "Can", "you", "recommend", "a", "good", "coffee", "shop", "around", "here", "How", "do", "I", "get", "to", "the", "local", "market",
        "What", "is", "the", "best", "way", "to", "explore", "the", "city", "Do", "you", "have", "any", "maps", "available", "Can", "you",
        "tell", "me", "the", "best", "place", "to", "visit", "around", "here", "How", "much", "does", "it", "cost", "to", "take", "a",
        "taxi", "to", "the", "downtown", "area", "What", "is", "the", "quickest", "way", "to", "get", "to", "the", "train", "station",
        "Do", "you", "know", "any", "good", "places", "to", "have", "dinner", "What", "time", "does", "the", "supermarket", "open",
        "Can", "you", "show", "me", "how", "to", "get", "to", "the", "nearest", "park", "How", "do", "I", "get", "a", "taxi",
        "What", "is", "the", "best", "way", "to", "experience", "the", "local", "culture", "Do", "you", "have", "any", "suggestions",
        "for", "places", "to", "visit", "around", "here", "Can", "you", "recommend", "a", "good", "restaurant", "in", "this", "area",
        "What", "time", "does", "the", "bus", "station", "close", "How", "do", "I", "get", "to", "the", "city", "center", "What",
        "is", "the", "quickest", "way", "to", "get", "to", "the", "airport", "Can", "you", "show", "me", "how", "to", "use", "the",
        "metro", "What", "is", "the", "best", "way", "to", "get", "to", "the", "downtown", "area", "Do", "you", "have", "a", "local",
        "map", "Can", "you", "tell", "me", "how", "to", "get", "to", "the", "nearest", "beach", "How", "do", "I", "get", "a", "bus",
        "pass", "What", "is", "the", "best", "way", "to", "see", "the", "sights", "around", "here", "Do", "you", "have", "a", "tourist",
        "guide", "Can", "you", "recommend", "a", "good", "place", "to", "stay", "How", "do", "I", "use", "the", "local", "transportation",
        "system", "What", "time", "does", "the", "museum", "close", "Is", "there", "a", "place", "to", "get", "breakfast", "nearby", "Can",
        "you", "help", "me", "find", "a", "doctor", "How", "much", "is", "a", "ticket", "to", "the", "theater", "What", "is", "the", "best",
        "way", "to", "get", "to", "the", "airport", "Do", "you", "know", "a", "good", "place", "to", "have", "lunch", "Where", "can", "I",
        "buy", "tickets", "for", "the", "train", "What", "time", "does", "the", "next", "bus", "arrive", "Can", "you", "recommend", "a",
        "good", "coffee", "shop", "around", "here", "How", "do", "I", "get", "to", "the", "local", "market", "What", "is", "the", "best",
        "way", "to", "explore", "the", "city", "Do", "you", "have", "any", "maps", "available", "Can", "you", "tell", "me", "the", "best",
        "place", "to", "visit", "around", "here", "How", "much", "does", "it", "cost", "to", "take", "a", "taxi", "to", "the", "downtown",
        "area", "What", "is", "the", "quickest", "way", "to", "get", "to", "the", "train", "station", "Do", "you", "know", "any", "good",
        "places", "to", "have", "dinner", "What", "time", "does", "the", "supermarket", "open", "Can", "you", "show", "me", "how", "to",
        "get", "to", "the", "nearest", "park", "How", "do", "I", "get", "a", "taxi", "What", "is", "the", "best", "way", "to", "experience",
        "the", "local", "culture", "Do", "you", "have", "any", "suggestions", "for", "places", "to", "visit", "around", "here", "Can",
        "you", "recommend", "a", "good", "restaurant", "in", "this", "area", "What", "time", "does", "the", "bus", "station", "close",
        "How", "do", "I", "get", "to", "the", "city", "center", "What", "is", "the", "quickest", "way", "to", "get", "to", "the",
        "airport", "Can", "you", "show", "me", "how", "to", "use", "the", "metro", "What", "is", "the", "best", "way", "to", "get",
        "to", "the", "downtown", "area", "Do", "you", "have", "a", "local", "map", "Can", "you", "tell", "me", "how", "to", "get",
        "to", "the", "nearest", "beach", "How", "do", "I", "get", "a", "bus", "pass", "What", "is", "the", "best", "way", "to",
        "see", "the", "sights", "around", "here", "Do", "you", "have", "a", "tourist", "guide", "Can", "you", "recommend", "a",
        "good", "place", "to", "stay", "How", "do", "I", "use", "the", "local", "transportation", "system", "What", "time", "does",
        "the", "museum", "close", "Is", "there", "a", "place", "to", "get", "breakfast", "nearby", "Can", "you", "help", "me",
        "find", "a", "doctor", "How", "much", "is", "a", "ticket", "to", "the", "theater", "What", "is", "the", "best", "way",
        "to", "get", "to", "the", "airport", "Do", "you", "know", "a", "good", "place", "to", "have", "lunch", "Where", "can",
        "I", "buy", "tickets", "for", "the", "train", "What", "time", "does", "the", "next", "bus", "arrive", "Can", "you",
        "recommend", "a", "good", "coffee", "shop", "around", "here", "How", "do", "I", "get", "to", "the", "local", "market",
        "What", "is", "the", "best", "way", "to", "explore", "the", "city", "Do", "you", "have", "any", "maps", "available",
        "Can", "you", "tell", "me", "the", "best", "place", "to", "visit", "around", "here", "How", "much", "does", "it",
        "cost", "to", "take", "a", "taxi", "to", "the", "downtown", "area", "What", "is", "the", "quickest", "way", "to",
        "get", "to", "the", "train", "station", "Do", "you", "know", "any", "good", "places", "to", "have", "dinner",
        "What", "time", "does", "the", "supermarket", "open", "Can", "you", "show", "me", "how", "to", "get", "to",
        "the", "nearest", "park", "How", "do", "I", "get", "a", "taxi", "What", "is", "the", "best", "way", "to",
        "experience", "the", "local", "culture", "Do", "you", "have", "any", "suggestions", "for", "places", "to",
        "visit", "around", "here", "Can", "you", "recommend", "a", "good", "restaurant", "in", "this", "area",
        "What", "time", "does", "the", "bus", "station", "close", "How", "do", "I", "get", "to", "the", "city",
        "center", "What", "is", "the", "quickest", "way", "to", "get", "to", "the", "airport", "Can", "you",
        "show", "me", "how", "to", "use", "the", "metro", "What", "is", "the", "best", "way", "to", "get",
        "to", "the", "downtown", "area", "Do", "you", "have", "a", "local", "map", "Can", "you", "tell",
        "me", "how", "to", "get", "to", "the", "nearest", "beach", "How", "do", "I", "get", "a", "bus",
        "pass", "What", "is", "the", "best", "way", "to", "see", "the", "sights", "around", "here",
        "Do", "you", "have", "a", "tourist", "guide", "Can", "you", "recommend", "a", "good", "place",
        "to", "stay", "How", "do", "I", "use", "the", "local", "transportation", "system", "What",
        "time", "does", "the", "museum", "close", "Is", "there", "a", "place", "to", "get", "breakfast",
        "nearby", "Can", "you", "help", "me", "find", "a", "doctor", "How", "much", "is", "a", "ticket",
        "to", "the", "theater", "What", "is", "the", "best", "way", "to", "get", "to", "the", "airport",
        "Do", "you", "know", "a", "good", "place", "to", "have", "lunch", "Where", "can", "I", "buy",
        "tickets", "for", "the", "train", "What", "time", "does", "the", "next", "bus", "arrive",
        "Can", "you", "recommend", "a", "good", "coffee", "shop", "around", "here", "How", "do", "I",
        "get", "to", "the", "local", "market", "What", "is", "the", "best", "way", "to", "explore",
        "the", "city", "Do", "you", "have", "any", "maps", "available", "Can", "you", "tell",
        "me", "the", "best", "place", "to", "visit", "around", "here", "How", "much", "does",
        "it", "cost", "to", "take", "a", "taxi", "to", "the", "downtown", "area", "What", "is",
        "the", "quickest", "way", "to", "get", "to", "the", "train", "station", "Do", "you", "know",
        "any", "good", "places", "to", "have", "dinner", "What", "time", "does", "the", "supermarket",
        "open", "Can", "you", "show", "me", "how", "to", "get", "to", "the", "nearest", "park",
        "How", "do", "I", "get", "a", "taxi", "What", "is", "the", "best", "way", "to", "experience",
        "the", "local", "culture", "Do", "you", "have", "any", "suggestions", "for", "places", "to",
        "visit", "around", "here", "Can", "you", "recommend", "a", "good", "restaurant", "in", "this",
        "area", "What", "time", "does", "the", "bus", "station", "close", "How", "do", "I", "get",
        "to", "the", "city", "center", "What", "is", "the", "quickest", "way", "to", "get", "to",
        "the", "airport", "Can", "you", "show", "me", "how", "to", "use", "the", "metro", "What",
        "is", "the", "best", "way", "to", "get", "to", "the", "downtown", "area", "Do", "you", "have",
        "a", "local", "map", "Can", "you", "tell", "me", "how", "to", "get", "to", "the", "nearest",
        "beach", "How", "do", "I", "get", "a", "bus", "pass", "What", "is", "the", "best", "way",
        "to", "see", "the", "sights", "around", "here", "Do", "you", "have", "a", "tourist", "guide",
        "Can", "you", "recommend", "a", "good", "place", "to", "stay", "How", "do", "I", "use", "the",
        "local", "transportation", "system", "What", "time", "does", "the", "museum", "close", "Is",
        "there", "a", "place", "to", "get", "breakfast", "nearby", "Can", "you", "help", "me",
        "find", "a", "doctor", "How", "much", "is", "a", "ticket", "to", "the", "theater", "What",
        "is", "the", "best", "way", "to", "get", "to", "the", "airport", "Do", "you", "know", "a",
        "good", "place", "to", "have", "lunch", "Where", "can", "I", "buy", "tickets", "for",
        "the", "train", "What", "time", "does", "the", "next", "bus", "arrive", "Can", "you",
        "recommend", "a", "good", "coffee", "shop", "around", "here", "How", "do", "I", "get",
        "to", "the", "local", "market", "What", "is", "the", "best", "way", "to", "explore",
        "the", "city", "Do", "you", "have", "any", "maps", "available", "Can", "you", "tell",
        "me", "the", "best", "place", "to", "visit", "around", "here", "How", "much", "does",
        "it", "cost", "to", "take", "a", "taxi", "to", "the", "downtown", "area", "What", "is",
        "the", "quickest", "way", "to", "get", "to", "the", "train", "station", "Do", "you",
        "know", "any", "good", "places", "to", "have", "dinner", "What", "time", "does",
        "the", "supermarket", "open", "Can", "you", "show", "me", "how", "to", "get",
        "to", "the", "nearest", "park", "How", "do", "I", "get", "a", "taxi", "What",
        "is", "the", "best", "way", "to", "experience", "the", "local", "culture", "Do",
        "you", "have", "any", "suggestions", "for", "places", "to", "visit", "around",
        "here", "Can", "you", "recommend", "a", "good", "restaurant", "in", "this",
        "area", "What", "time", "does", "the", "bus", "station", "close", "How",
        "do", "I", "get", "to", "the", "city", "center", "What", "is", "the",
        "quickest", "way", "to", "get", "to", "the", "airport", "Can", "you",
        "show", "me", "how", "to", "use", "the", "metro", "What", "is",
        "the", "best", "way", "to", "get", "to", "the", "downtown", "area",
        "Do", "you", "have", "a", "local", "map", "Can", "you", "tell",
        "me", "how", "to", "get", "to", "the", "nearest", "beach", "How",
        "do", "I", "get", "a", "bus", "pass", "What", "is", "the", "best",
        "way", "to", "see", "the", "sights", "around", "here", "Do", "you",
        "have", "a", "tourist", "guide", "Can", "you", "recommend", "a",
        "good", "place", "to", "stay", "How", "do", "I", "use", "the",
        "local", "transportation", "system", "What", "time", "does",
        "the", "museum", "close", "Is", "there", "a", "place", "to",
        "get", "breakfast", "nearby", "Can", "you", "help", "me",
        "find", "a", "doctor", "How", "much", "is", "a", "ticket",
        "to", "the", "theater", "What", "is", "the", "best", "way",
        "to", "get", "to", "the", "airport", "Do", "you", "know",
        "a", "good", "place", "to", "have", "lunch", "Where",
        "can", "I", "buy", "tickets", "for", "the", "train",
        "What", "time", "does", "the", "next", "bus", "arrive",
        "Can", "you", "recommend", "a", "good", "coffee",
        "shop", "around", "here", "How", "do", "I", "get",
        "to", "the", "local", "market", "What", "is",
        "the", "best", "way", "to", "explore", "the",
        "city", "Do", "you", "have", "any", "maps",
        "available", "Can", "you", "tell", "me",
        "the", "best", "place", "to", "visit",
        "around", "here", "How", "much",
        "does", "it", "cost", "to", "take",
        "a", "taxi", "to", "the", "downtown",
        "area", "What", "is", "the", "quickest",
        "way", "to", "get", "to", "the", "train",
        "station", "Do", "you", "know", "any",
        "good", "places", "to", "have", "dinner",
        "What", "time", "does", "the", "supermarket",
        "open", "Can", "you", "show", "me", "how",
        "to", "get", "to", "the", "nearest",
        "park", "How", "do", "I", "get", "a",
        "taxi", "What", "is", "the", "best",
        "way", "to", "experience", "the",
        "local", "culture", "Do", "you",
        "have", "any", "suggestions",
        "for", "places", "to", "visit",
        "around", "here", "Can",
        "you", "recommend", "a",
        "good", "restaurant", "in",
        "this", "area", "What",
        "time", "does", "the",
        "bus", "station", "close",
        "How", "do", "I", "get",
        "to", "the", "city", "center",
        "What", "is", "the", "quickest",
        "way", "to", "get", "to", "the",
        "airport", "Can", "you", "show",
        "me", "how", "to", "use",
        "the", "metro", "What",
        "is", "the", "best", "way",
        "to", "get", "to", "the",
        "downtown", "area", "Do",
        "you", "have", "a", "local",
        "map", "Can", "you", "tell",
        "me", "how", "to", "get",
        "to", "the", "nearest",
        "beach", "How", "do", "I",
        "get", "a", "bus", "pass",
        "What", "is", "the", "best",
        "way", "to", "see", "the",
        "sights", "around", "here",
        "Do", "you", "have", "a",
        "tourist", "guide", "Can",
        "you", "recommend", "a",
        "good", "place", "to", "stay",
        "How", "do", "I", "use", "the",
        "local", "transportation",
        "system", "What", "time",
        "does", "the", "museum",
        "close", "Is", "there",
        "a", "place", "to", "get",
        "breakfast", "nearby",
        "Can", "you", "help",
        "me", "find", "a", "doctor",
        "How", "much", "is", "a",
        "ticket", "to", "the",
        "theater", "What", "is",
        "the", "best", "way",
        "to", "get", "to", "the",
        "airport", "Do", "you",
        "know", "a", "good", "place",
        "to", "have", "lunch", "Where",
        "can", "I", "buy", "tickets",
        "for", "the", "train", "What",
        "time", "does", "the", "next",
        "bus", "arrive", "Can",
        "you", "recommend", "a",
        "good", "coffee", "shop",
        "around", "here", "How",
        "do", "I", "get", "to",
        "the", "local", "market",
        "What", "is", "the",
        "best", "way", "to",
        "explore", "the", "city",
        "Do", "you", "have", "any",
        "maps", "available", "Can",
        "you", "tell", "me", "the",
        "best", "place", "to",
        "visit", "around", "here",
        "How", "much", "does", "it",
        "cost", "to", "take", "a",
        "taxi", "to", "the", "downtown",
        "area", "What", "is", "the",
        "quickest", "way", "to", "get",
        "to", "the", "train", "station",
        "Do", "you", "know", "any",
        "good", "places", "to",
        "have", "dinner", "What",
        "time", "does", "the",
        "supermarket", "open",
        "Can", "you", "show", "me",
        "how", "to", "get", "to",
        "the", "nearest", "park",
        "How", "do", "I", "get", "a",
        "taxi", "What", "is", "the",
        "best", "way", "to",
        "experience", "the", "local",
        "culture", "Do", "you",
        "have", "any", "suggestions",
        "for", "places", "to",
        "visit", "around", "here",
        "Can", "you", "recommend",
        "a", "good", "restaurant",
        "in", "this", "area", "What",
        "time", "does", "the",
        "bus", "station", "close",
        "How", "do", "I", "get", "to",
        "the", "city", "center",
        "What", "is", "the",
        "quickest", "way", "to",
        "get", "to", "the", "airport",
        "Can", "you", "show", "me",
        "how", "to", "use", "the",
        "metro", "What", "is", "the",
        "best", "way", "to", "get",
        "to", "the", "downtown",
        "area", "Do", "you", "have",
        "a", "local", "map", "Can",
        "you", "tell", "me", "how",
        "to", "get", "to", "the",
        "nearest", "beach", "How",
        "do", "I", "get", "a", "bus",
        "pass", "What", "is", "the",
        "best", "way", "to", "see",
        "the", "sights", "around",
        "here", "Do", "you", "have",
        "a", "tourist", "guide",
        "Can", "you", "recommend",
        "a", "good", "place", "to",
        "stay", "How", "do", "I",
        "use", "the", "local",
        "transportation", "system",
        "What", "time", "does",
        "the", "museum", "close",
        "Is", "there", "a", "place",
        "to", "get", "breakfast",
        "nearby", "Can", "you",
        "help", "me", "find", "a",
        "doctor", "How", "much",
        "is", "a", "ticket", "to",
        "the", "theater", "What",
        "is", "the", "best", "way",
        "to", "get", "to", "the",
        "airport", "Do", "you",
        "know", "a", "good", "place",
        "to", "have", "lunch", "Where",
        "can", "I", "buy", "tickets",
        "for", "the", "train", "What",
        "time", "does", "the", "next",
        "bus", "arrive", "Can", "you",
        "recommend", "a", "good",
        "coffee", "shop", "around",
        "here", "How", "do", "I",
        "get", "to", "the", "local",
        "market", "What", "is",
        "the", "best", "way", "to",
        "explore", "the", "city",
        "Do", "you", "have", "any",
        "maps", "available", "Can",
        "you", "tell", "me", "the",
        "best", "place", "to",
        "visit", "around", "here",
        "How", "much", "does", "it",
        "cost", "to", "take", "a",
        "taxi", "to", "the", "downtown",
        "area", "What", "is", "the",
        "quickest", "way", "to",
        "get", "to", "the", "train",
        "station", "Do", "you",
        "know", "any", "good",
        "places", "to", "have",
        "dinner", "What", "time",
        "does", "the", "supermarket",
        "open", "Can", "you", "show",
        "me", "how", "to", "get",
        "to", "the", "nearest",
        "park", "How", "do", "I",
        "get", "a", "taxi", "What",
        "is", "the", "best", "way",
        "to", "experience", "the",
        "local", "culture", "Do",
        "you", "have", "any",
        "suggestions", "for",
        "places", "to", "visit",
        "around", "here", "Can",
        "you", "recommend", "a",
        "good", "restaurant",
        "in", "this", "area",
        "What", "time", "does",
        "the", "bus", "station",
        "close", "How", "do",
        "I", "get", "to", "the",
        "city", "center", "What",
        "is", "the", "quickest",
        "way", "to", "get", "to",
        "the", "airport", "Can",
        "you", "show", "me", "how",
        "to", "use", "the", "metro",
        "What", "is", "the", "best",
        "way", "to", "get", "to",
        "the", "downtown", "area",
        "Do", "you", "have", "a",
        "local", "map", "Can", "you",
        "tell", "me", "how", "to",
        "get", "to", "the", "nearest",
        "beach", "How", "do", "I",
        "get", "a", "bus", "pass",
        "What", "is", "the", "best",
        "way", "to", "see", "the",
        "sights", "around", "here",
        "Do", "you", "have", "a",
        "tourist", "guide", "Can",
        "you", "recommend", "a",
        "good", "place", "to", "stay",
        "How", "do", "I", "use", "the",
        "local", "transportation",
        "system", "What", "time",
        "does", "the", "museum",
        "close", "Is", "there",
        "a", "place", "to", "get",
        "breakfast", "nearby",
        "Can", "you", "help", "me",
        "find", "a", "doctor",
        "How", "much", "is", "a",
        "ticket", "to", "the",
        "theater", "What", "is",
        "the", "best", "way",
        "to", "get", "to", "the",
        "airport", "Do", "you",
        "know", "a", "good", "place",
        "to", "have", "lunch",
        "Where", "can", "I", "buy",
        "tickets", "for", "the",
        "train", "What", "time",
        "does", "the", "next",
        "bus", "arrive", "Can",
        "you", "recommend", "a",
        "good", "coffee", "shop",
        "around", "here", "How",
        "do", "I", "get", "to",
        "the", "local", "market",
        "What", "is", "the",
        "best", "way", "to",
        "explore", "the", "city",
        "Do", "you", "have", "any",
        "maps", "available", "Can",
        "you", "tell", "me", "the",
        "best", "place", "to",
        "visit", "around", "here",
        "How", "much", "does", "it",
        "cost", "to", "take", "a",
        "taxi", "to", "the", "downtown",
        "area", "What", "is", "the",
        "quickest", "way", "to",
        "get", "to", "the", "train",
        "station", "Do", "you",
        "know", "any", "good",
        "places", "to", "have",
        "dinner", "What", "time",
        "does", "the", "supermarket",
        "open", "Can", "you", "show",
        "me", "how", "to", "get",
        "to", "the", "nearest",
        "park", "How", "do", "I",
        "get", "a", "taxi", "What",
        "is", "the", "best", "way",
        "to", "experience", "the",
        "local", "culture", "Do",
        "you", "have", "any",
        "suggestions", "for",
        "places", "to", "visit",
        "around", "here", "Can",
        "you", "recommend", "a",
        "good", "restaurant",
        "in", "this", "area",
        "What", "time", "does",
        "the", "bus", "station",
        "close", "How", "do",
        "I", "get", "to", "the",
        "city", "center", "What",
        "is", "the", "quickest",
        "way", "to", "get", "to",
        "the", "airport", "Can",
        "you", "show", "me", "how",
        "to", "use", "the", "metro",
        "What", "is", "the", "best",
        "way", "to", "get", "to",
        "the", "downtown", "area",
        "Do", "you", "have", "a",
        "local", "map", "Can", "you",
        "tell", "me", "how", "to",
        "get", "to", "the", "nearest",
        "beach", "How", "do", "I",
        "get", "a", "bus", "pass",
        "What", "is", "the", "best",
        "way", "to", "see", "the",
        "sights", "around", "here",
        "Do", "you", "have", "a",
        "tourist", "guide", "Can",
        "you", "recommend", "a",
        "good", "place", "to", "stay",
        "How", "do", "I", "use", "the",
        "local", "transportation",
        "system", "What", "time",
        "does", "the", "museum",
        "close", "Is", "there",
        "a", "place", "to", "get",
        "breakfast", "nearby",
        "Can", "you", "help", "me",
        "find", "a", "doctor",
        "How", "much", "is", "a",
        "ticket", "to", "the",
        "theater", "What", "is",
        "the", "best", "way",
        "to", "get", "to", "the",
        "airport", "Do", "you",
        "know", "a", "good", "place",
        "to", "have", "lunch",
        "Where", "can", "I", "buy",
        "tickets", "for", "the",
        "train", "What", "time",
        "does", "the", "next",
        "bus", "arrive", "Can",
        "you", "recommend", "a",
        "good", "coffee", "shop",
        "around", "here", "How",
        "do", "I", "get", "to",
        "the", "local", "market",
        "What", "is", "the",
        "best", "way", "to",
        "explore", "the", "city",
        "Do", "you", "have", "any",
        "maps", "available", "Can",
        "you", "tell", "me", "the",
        "best", "place", "to",
        "visit", "around", "here",
        "How", "much", "does", "it",
        "cost", "to", "take", "a",
        "taxi", "to", "the", "downtown",
        "area", "What", "is", "the",
        "quickest", "way", "to",
        "get", "to", "the", "train",
        "station", "Do", "you",
        "know", "any", "good",
        "places", "to", "have",
        "dinner", "What", "time",
        "does", "the", "supermarket",
        "open", "Can", "you", "show",
        "me", "how", "to", "get",
        "to", "the", "nearest",
        "park", "How", "do", "I",
        "get", "a", "taxi", "What",
        "is", "the", "best", "way",
        "to", "experience", "the",
        "local", "culture", "Do",
        "you", "have", "any",
        "suggestions", "for",
        "places", "to", "visit",
        "around", "here", "Can",
        "you", "recommend", "a",
        "good", "restaurant",
        "in", "this", "area",
        "What", "time", "does",
        "the", "bus", "station",
        "close", "How", "do",
        "I", "get", "to", "the",
        "city", "center", "What",
        "is", "the", "quickest",
        "way", "to", "get", "to",
        "the", "airport", "Can",
        "you", "show", "me", "how",
        "to", "use", "the", "metro",
        "What", "is", "the", "best",
        "way", "to", "get", "to",
        "the", "downtown", "area",
        "Do", "you", "have", "a",
        "local", "map", "Can", "you",
        "tell", "me", "how", "to",
        "get", "to", "the", "nearest",
        "beach", "How", "do", "I",
        "get", "a", "bus", "pass",
        "What", "is", "the", "best",
        "way", "to", "see", "the",
        "sights", "around", "here",
        "Do", "you", "have", "a",
        "tourist", "guide", "Can",
        "you", "recommend", "a",
        "good", "place", "to", "stay",
        "How", "do", "I", "use", "the",
        "local", "transportation",
        "system", "What", "time",
        "does", "the", "museum",
        "close", "Is", "there",
        "a", "place", "to", "get",
        "breakfast", "nearby",
        "Can", "you", "help",
        "me", "find", "a", "doctor"
    }; // Test data example

    std::unordered_map<std::string, std::vector<double>> embeddings;
    for (const auto& word : trainingData) {
        embeddings[word] = generateRandomEmbedding();
    }
    for (const auto& word : testData) {
        if (embeddings.find(word) == embeddings.end()) {
            embeddings[word] = generateRandomEmbedding();
        }
    }

    embeddings[PAD_TOKEN] = std::vector<double>(EMBEDDING_SIZE, 0.0);

    trainModel(embeddings, trainingData);

    evaluateModel(embeddings, testData);

    std::string inputSentence;
    std::cout << "Training [ done ]\nEnter a sentence: ";
    std::getline(std::cin, inputSentence);

    std::vector<std::string> tokens = tokenize(inputSentence);
    padAndMask(tokens, CONTEXT_SIZE);
    std::vector<double> contextEmbedding = aggregateEmbeddings(tokens, embeddings);
    std::string nextToken = predictNextToken(contextEmbedding, embeddings);

    std::cout << "Predicted next token: " << nextToken << "\n";

    return 0;
}
